package sql

import (
	"fmt"

	"github.com/88250/lute/ast"
	"github.com/siyuan-note/siyuan/kernel/av"
	"github.com/siyuan-note/siyuan/kernel/util"
)

func RenderAttributeViewCalendar(attrView *av.AttributeView, view *av.View, query string, depth *int, cachedAttrViews map[string]*av.AttributeView, ignoreRows bool) (ret *av.Calendar) {
	viewable := attrView.RenderedViewables[view.ID]
	if nil != viewable {
		ret = viewable.(*av.Calendar)
		return
	}

	ret = &av.Calendar{
		BaseInstance: av.NewViewBaseInstance(view),
		Fields:       []*av.CalendarField{},
		Cards:        []*av.CalendarCard{},
	}

	if nil != view.Calendar {
		ret.DateFieldID = view.Calendar.DateFieldID
		ret.ViewMode = view.Calendar.ViewMode
		ret.WeekStart = view.Calendar.WeekStart
		ret.NewItemTarget = view.Calendar.NewItemTarget
		ret.FieldMapping = view.Calendar.FieldMapping

		fields := make([]*av.ViewCalendarCardField, len(view.Calendar.Fields))
		copy(fields, view.Calendar.Fields)
		for _, field := range fields {
			key, getErr := attrView.GetKey(field.ID)
			if nil != getErr {
				// 找不到字段则在视图中删除（元数据查询场景不写盘）
				if !ignoreRows {
					removeMissingField(attrView, view, field.ID)
				}
				continue
			}

			ret.Fields = append(ret.Fields, &av.CalendarField{
				BaseInstanceField: &av.BaseInstanceField{
					ID:           key.ID,
					Name:         key.Name,
					Type:         key.Type,
					Icon:         key.Icon,
					Wrap:         field.Wrap,
					Hidden:       field.Hidden,
					Desc:         key.Desc,
					Calc:         field.Calc,
					Options:      key.Options,
					NumberFormat: key.NumberFormat,
					Template:     key.Template,
					Relation:     key.Relation,
					Rollup:       key.Rollup,
					Date:         key.Date,
					Created:      key.Created,
					Updated:      key.Updated,
				},
			})
		}
	}

	// 菜单等只需要字段/视图元数据的场景，跳过全部卡片处理
	if ignoreRows {
		return
	}

	cardsValues := generateAttrViewItems(attrView, view)
	filterNotFoundAttrViewItems(cardsValues)

	for cardID, cardValues := range cardsValues {
		var calendarCard av.CalendarCard
		calendarCard.ID = cardID
		for _, field := range ret.Fields {
			var fieldValue *av.CalendarFieldValue
			for _, keyValues := range cardValues {
				if keyValues.Key.ID == field.ID {
					if 0 < len(keyValues.Values) {
						fieldValue = &av.CalendarFieldValue{
							BaseValue: &av.BaseValue{
								ID:        keyValues.Values[0].ID,
								Value:     keyValues.Values[0],
								ValueType: field.Type,
							},
						}
					}
					break
				}
			}
			if nil == fieldValue {
				fieldValue = &av.CalendarFieldValue{
					BaseValue: &av.BaseValue{
						ID:        cardID[:14] + ast.NewNodeID()[14:],
						ValueType: field.Type,
					},
				}
			}

			fieldDateIsTime := false
			if nil != field.Date {
				fieldDateIsTime = field.Date.FillSpecificTime
			}
			fillAttributeViewBaseValue(fieldValue.BaseValue, field.ID, cardID, field.NumberFormat, field.Template, fieldDateIsTime)
			calendarCard.Values = append(calendarCard.Values, fieldValue)
		}

		ret.Cards = append(ret.Cards, &calendarCard)
	}

	fillAttributeViewKeyValues(attrView, ret)

	var ialIDs []string
	for _, card := range ret.Cards {
		blockVal := card.GetBlockValue()
		if nil != blockVal && !blockVal.IsDetached && nil != blockVal.Block {
			ialIDs = append(ialIDs, blockVal.Block.ID)
		}
	}
	ials := BatchGetBlockAttrs(ialIDs)

	fillAttributeViewAutoGeneratedValues(attrView, ret, ials, depth, cachedAttrViews)

	renderTemplateErr := fillAttributeViewTemplateValues(attrView, view, ret, ials)
	if nil != renderTemplateErr {
		util.PushErrMsg(fmt.Sprintf(util.Langs[util.Lang][44], util.EscapeHTML(renderTemplateErr.Error())), 30000)
	}

	filterByQuery(query, ret)
	manualSort(view, ret)

	attrView.RenderedViewables[view.ID] = ret
	return
}
