import type {Transaction, TransactionOperation, UnknownTransactionAction} from "../../types/api";

const transactionActions: Record<IOperation["action"], true> = {
    "setAttrViewCalendar": true,
    "updateAttrs": true,
    "create": true,
    "restoreCreatedDoc": true,
    "removeCreatedDoc": true,
    "update": true,
    "insert": true,
    "delete": true,
    "move": true,
    "swapBlockRef": true,
    "moveOutlineHeading": true,
    "append": true,
    "appendInsert": true,
    "prependInsert": true,
    "foldHeading": true,
    "unfoldHeading": true,
    "setAttrs": true,
    "doUpdateUpdated": true,
    "addFlashcards": true,
    "removeFlashcards": true,
    "setAttrViewName": true,
    "setAttrViewNewItemTemplates": true,
    "setAttrViewFilters": true,
    "setAttrViewContextFilter": true,
    "setAttrViewColRelationFilters": true,
    "setAttrViewColRollupFilters": true,
    "setAttrViewSorts": true,
    "setAttrViewPageSize": true,
    "setAttrViewColWidth": true,
    "setAttrViewColsWidth": true,
    "setAttrViewColAlign": true,
    "setAttrViewColWrap": true,
    "setAttrViewColHidden": true,
    "setAttrViewColPin": true,
    "setAttrViewColIcon": true,
    "setAttrViewColDesc": true,
    "insertAttrViewBlock": true,
    "removeAttrViewBlock": true,
    "addAttrViewCol": true,
    "updateAttrViewCol": true,
    "removeAttrViewCol": true,
    "sortAttrViewRow": true,
    "sortAttrViewCol": true,
    "sortAttrViewKey": true,
    "sortAttrViewBinding": true,
    "updateAttrViewCell": true,
    "updateAttrViewCells": true,
    "updateAttrViewColOptions": true,
    "removeAttrViewColOption": true,
    "updateAttrViewColOption": true,
    "setAttrViewColOptionDesc": true,
    "setAttrViewCustomColors": true,
    "setAttrViewColCalc": true,
    "updateAttrViewColNumberFormat": true,
    "setAttrViewColDateFormat": true,
    "replaceAttrViewBlock": true,
    "updateAttrViewColTemplate": true,
    "addAttrViewView": true,
    "removeAttrViewView": true,
    "setAttrViewViewName": true,
    "setAttrViewViewIcon": true,
    "setAttrViewViewDesc": true,
    "duplicateAttrViewView": true,
    "duplicateAttrViewRow": true,
    "sortAttrViewView": true,
    "updateAttrViewColRelation": true,
    "updateAttrViewColRollup": true,
    "hideAttrViewName": true,
    "setAttrViewColDateFillCreated": true,
    "setAttrViewColDateFillSpecificTime": true,
    "setAttrViewCreatedIncludeTime": true,
    "setAttrViewUpdatedIncludeTime": true,
    "duplicateAttrViewKey": true,
    "setAttrViewCoverFrom": true,
    "setAttrViewCoverFromAssetKeyID": true,
    "setAttrViewCardCoverPosition": true,
    "setAttrViewCardSize": true,
    "setAttrViewCardWidth": true,
    "setAttrViewCardLayout": true,
    "setAttrViewColFullRow": true,
    "setAttrViewFitImage": true,
    "setAttrViewDisplayFieldName": true,
    "setAttrViewDisplayEmptyFields": true,
    "setAttrViewFillColBackgroundColor": true,
    "setAttrViewShowIcon": true,
    "setAttrViewWrapField": true,
    "changeAttrViewLayout": true,
    "setAttrViewBlockView": true,
    "setAttrViewBlockVisibleViews": true,
    "setAttrViewCardAspectRatio": true,
    "setAttrViewCardAspectRatioValue": true,
    "setAttrViewGroup": true,
    "hideAttrViewGroup": true,
    "hideAttrViewAllGroups": true,
    "foldAttrViewGroup": true,
    "foldAttrViewGroups": true,
    "syncAttrViewTableColWidth": true,
    "removeAttrViewGroup": true,
    "sortAttrViewGroup": true,
};

type KnownTransactionOperation = Exclude<TransactionOperation, {action: UnknownTransactionAction}>;

export const isKnownTransactionOperation = (operation: TransactionOperation): operation is KnownTransactionOperation =>
    !!operation && Object.prototype.hasOwnProperty.call(transactionActions, operation.action);

// 编辑器只应用能够识别的操作，插件扩展操作仍由原始接口响应和事务事件传递。
export const getEditorTransaction = (value: Transaction) => ({
    ...value,
    doOperations: value.doOperations?.filter(isKnownTransactionOperation) ?? null,
    undoOperations: value.undoOperations?.filter(isKnownTransactionOperation) ?? null,
});
