name: ✨ 新功能请求
description: 提出您期望的功能
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > 我们目前不再接受关系图相关的新功能提议。
  - type: checkboxes
    attributes:
      label: 提交前确认
      description: |
        请完成以下所有确认。
      options:
        - label: 我已搜索现有 issue
          required: true
        - label: 本 issue 仅包含一个功能提议
          required: true
        - label: 本提议与关系图无关
          required: true
  - type: textarea
    attributes:
      label: 该功能将解决什么问题？
      description: |
        请尽可能清晰准确地描述需要解决的问题及其应用场景。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述预期结果或建议方案
      description: |
        请描述预期结果或您的建议方案。如果其他软件提供了类似功能，请一并列出以供我们参考。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 其他信息
      description: |
        请提供其他相关背景、截图、链接或相关 issue。
    validations:
      required: false
